import test from 'node:test';import assert from 'node:assert/strict';import dgram from 'node:dgram';import {once} from 'node:events';import {mkdtemp,rm} from 'node:fs/promises';import {tmpdir} from 'node:os';import {join} from 'node:path';
import {createBridge,DemoAdapter,artDmxPacket,ArtNetAdapter,readLastTarget,selectTarget} from '../bridge/server.mjs';import {newStrip} from '../dist/modules/model.js';
test('ArtDMX packet has correct byte order, protocol, address, and even length',()=>{const p=artDmxPacket(258,[1,2,3],42);assert.equal(p.subarray(0,8).toString(),'Art-Net\0');assert.equal(p.readUInt16LE(8),0x5000);assert.equal(p.readUInt16BE(10),14);assert.equal(p.readUInt16LE(14),258);assert.equal(p.readUInt16BE(16),4);assert.equal(p[12],42);assert.deepEqual([...p.subarray(18)],[1,2,3,0]);});
test('Art-Net adapter writes RGBA values across a universe split',async t=>{const adapter=new ArtNetAdapter('127.0.0.1');adapter.flush=async()=>{};t.after(()=>adapter.close());const s=newStrip(0,1,3);Object.assign(s,{type:'rgba',channel:511,universePolicy:'channel',order:'grb'});await adapter.configure([s]);await adapter.pixel(s,0,[10,20,30]);assert.deepEqual([...adapter.frames.get(3).subarray(510,512)],[20,10]);assert.deepEqual([...adapter.frames.get(4).subarray(0,2)],[30,255]);});
test('bridge authentication, CORS, configuration, exclusive pixels, validation and blackout',async t=>{const adapter=new DemoAdapter(),bridge=createBridge({adapter,token:'test-token'});bridge.server.listen(0,'127.0.0.1');await once(bridge.server,'listening');t.after(()=>bridge.close());const url=`http://127.0.0.1:${bridge.server.address().port}`;const request=(path,body,extra={})=>fetch(url+path,{method:body?'POST':'GET',headers:{Authorization:'Bearer test-token','Content-Type':'application/json',...extra},body:body?JSON.stringify(body):undefined});assert.equal((await fetch(url+'/api/health')).status,401);assert.equal((await request('/api/health',null,{Origin:'https://evil.example'})).status,403);const health=await request('/api/health',null,{Origin:'https://benkuper.github.io'});assert.equal(health.headers.get('Access-Control-Allow-Origin'),'https://benkuper.github.io');assert.equal((await health.json()).protocol,'stripr/1');const strip=newStrip(0,60);assert.equal((await request('/api/configure',{strips:[strip]})).status,200);assert.equal((await request('/api/pixel',{strip:strip.id,index:3,rgb:[100,0,0]})).status,200);assert.equal(adapter.current.index,3);await request('/api/pixel',{strip:strip.id,index:4,rgb:[0,0,100]});assert.equal(adapter.current.index,4);assert.equal((await request('/api/pixel',{strip:strip.id,index:60,rgb:[1,2,3]})).status,400);assert.equal((await request('/api/pixel',{strip:strip.id,index:0,rgb:[999,0,0]})).status,400);await request('/api/blackout',{});assert.equal(adapter.current,null);const home=await fetch(url+'/');assert.equal(home.status,200);assert.match(await home.text(),/Map your light/);});
test('watchdog clears output after a lost client',async t=>{const adapter=new DemoAdapter(),bridge=createBridge({adapter,token:'x',watchdogMs:20});bridge.server.listen(0,'127.0.0.1');await once(bridge.server,'listening');t.after(()=>bridge.close());const url=`http://127.0.0.1:${bridge.server.address().port}`,strip=newStrip(0);const post=(path,body)=>fetch(url+path,{method:'POST',headers:{Authorization:'Bearer x','Content-Type':'application/json'},body:JSON.stringify(body)});await post('/api/configure',{strips:[strip]});await post('/api/pixel',{strip:strip.id,index:1,rgb:[1,2,3]});assert.ok(adapter.current);await new Promise(r=>setTimeout(r,320));assert.equal(adapter.current,null);});
test('Pages origin can use the default bridge without authentication',async t=>{const bridge=createBridge();bridge.server.listen(0,'127.0.0.1');await once(bridge.server,'listening');t.after(()=>bridge.close());const url=`http://127.0.0.1:${bridge.server.address().port}`,origin='https://benkuper.github.io';const preflight=await fetch(url+'/api/configure',{method:'OPTIONS',headers:{Origin:origin,'Access-Control-Request-Method':'POST','Access-Control-Request-Private-Network':'true'}});assert.equal(preflight.status,204);assert.equal(preflight.headers.get('Access-Control-Allow-Origin'),origin);assert.equal(preflight.headers.get('Access-Control-Allow-Private-Network'),'true');const configured=await fetch(url+'/api/configure',{method:'POST',headers:{Origin:origin,'Content-Type':'application/json'},body:JSON.stringify({strips:[newStrip(0)]})});assert.equal(configured.status,200);});
test('target prompt remembers explicit and prompted targets and reuses the last default',async t=>{
  const dir=await mkdtemp(join(tmpdir(),'stripr-test-'));t.after(()=>rm(dir,{recursive:true,force:true}));const configFile=join(dir,'config.json');let prompts=0;
  assert.equal(await selectTarget({},{configFile,ask:async last=>{prompts++;assert.equal(last,'');return '192.168.1.50';}}),'192.168.1.50');
  assert.equal(await readLastTarget(configFile),'192.168.1.50');
  assert.equal(await selectTarget({},{configFile,ask:async last=>{prompts++;assert.equal(last,'192.168.1.50');return '';}}),'192.168.1.50');
  assert.equal(await selectTarget({target:'controller.local'},{configFile,ask:async()=>{throw new Error('should not prompt');}}),'controller.local');
  assert.equal(await readLastTarget(configFile),'controller.local');assert.equal(prompts,2);
});
