import test from 'node:test';import assert from 'node:assert/strict';
import {newStrip,newProject,pixelAddress,pixelChannels,validatePatch,validateProject,serializeProject,demoPosition} from '../dist/modules/model.js';
import {detectPixel} from '../dist/modules/detection.js';import {fitStraightStrip,probeIndices} from '../dist/modules/lines.js';import {exportResolume} from '../dist/modules/resolume.js';
test('RGB pixels stay together at universe boundaries and non-default channels',()=>{const s=newStrip(0,400,7);assert.deepEqual(pixelAddress(s,169),{universe:7,channel:508});assert.deepEqual(pixelAddress(s,170),{universe:8,channel:1});s.channel=509;assert.deepEqual(pixelAddress(s,0),{universe:7,channel:509});assert.deepEqual(pixelAddress(s,1),{universe:8,channel:1});});
test('RGBA width and both universe jump policies are applied channel by channel',()=>{const s=newStrip(0,200,7);s.type='rgba';s.channel=509;assert.deepEqual(pixelChannels(s,0),[{universe:7,channel:509},{universe:7,channel:510},{universe:7,channel:511},{universe:7,channel:512}]);assert.deepEqual(pixelAddress(s,1),{universe:8,channel:1});s.channel=511;s.universePolicy='channel';assert.deepEqual(pixelChannels(s,0),[{universe:7,channel:511},{universe:7,channel:512},{universe:8,channel:1},{universe:8,channel:2}]);assert.deepEqual(pixelAddress(s,1),{universe:8,channel:3});});
test('LED-boundary policy rejects a first LED that cannot fit',()=>{const s=newStrip(0);s.type='rgba';s.channel=510;assert.throws(()=>validatePatch([s]),/does not fit/);s.universePolicy='channel';assert.equal(validatePatch([s]),60);});
test('patch rejects overlaps, duplicate IDs, and universe overflow',()=>{const a=newStrip(0,171,0),b=newStrip(1,60,1);assert.throws(()=>validatePatch([a,b]),/overlap/);assert.throws(()=>validatePatch([a,{...a}]),/unique/);assert.throws(()=>validatePatch([{...a,universe:255}]),/255/);b.universe=2;assert.equal(validatePatch([a,b]),231);});
test('JSON round trip preserves missing indices and validates hostile input',()=>{const p=newProject();p.strips[0].points[5]={x:.2,y:.3,confidence:.7,source:'interpolated'};const round=validateProject(JSON.parse(serializeProject(p)));assert.deepEqual(round,p);assert.equal(round.strips[0].points[0],null);assert.throws(()=>validateProject({...p,strips:[{...p.strips[0],points:[{x:NaN,y:1}]}]}));assert.throws(()=>validateProject({...p,settings:{...p.settings,delay:-1}}));});
test('legacy projects default to RGB LEDs and whole-LED universe jumps',()=>{const p=newProject();delete p.strips[0].type;delete p.strips[0].universePolicy;const migrated=validateProject(p);assert.equal(migrated.strips[0].type,'rgb');assert.equal(migrated.strips[0].universePolicy,'led');});
function frames(spots){const width=60,height=40,dark=new Uint8Array(width*height*4),light=new Uint8Array(dark.length);dark.fill(20);light.fill(20);for(const [x,y,v] of spots)for(let dy=0;dy<3;dy++)for(let dx=0;dx<3;dx++){const at=((y+dy)*width+x+dx)*4;light[at]=v;light[at+1]=v;light[at+2]=v;}return{dark,light,width,height};}
test('differential detection finds centroid, rejects missing LEDs and similar reflections',()=>{const settings=newProject().settings;let f=frames([[10,15,230]]),p=detectPixel(f.dark,f.light,f.width,f.height,settings);assert.ok(Math.abs(p.x-11.5/60)<.001);assert.ok(Math.abs(p.y-16.5/40)<.001);f=frames([]);assert.equal(detectPixel(f.dark,f.light,f.width,f.height,settings),null);f=frames([[10,15,230],[40,15,220]]);assert.equal(detectPixel(f.dark,f.light,f.width,f.height,settings),null);});
test('straight-strip optimization verifies probes and marks all inferred coordinates',()=>{const points=Array(60).fill(null);for(const i of probeIndices(60))points[i]={x:.1+.8*i/59,y:.7-.4*i/59,confidence:.9,source:'scan'};const fit=fitStraightStrip(points,60);assert.ok(fit);assert.equal(fit.points.filter(p=>p.source==='interpolated').length,55);assert.equal(fit.points[0],points[0]);points[15]={...points[15],y:.95};assert.equal(fitStraightStrip(points,60),null);points[15]=null;assert.equal(fitStraightStrip(points,60),null);});
test('curved and unevenly spaced probe positions fall back to full scan',()=>{for(const type of ['curve','uneven']){const pts=Array(60).fill(null);for(const i of probeIndices(60)){const t=i/59;pts[i]={x:.1+.8*(type==='uneven'?t*t:t),y:.5+(type==='curve'?.1*Math.sin(t*Math.PI):0),confidence:1,source:'scan'};}assert.equal(fitStraightStrip(pts,60),null);}});
test('Resolume exports embedded fixtures, correct reserved channels, and XML escaping',()=>{const p=newProject();p.name='A & B <test>';p.strips=[newStrip(0,171,15)];p.strips[0].name='"LED" & <strip>';p.strips[0].points[0]={x:0,y:0,confidence:1,source:'scan'};p.strips[0].points[2]={x:.5,y:.5,confidence:1,source:'manual'};p.strips[0].points[170]={x:1,y:1,confidence:1,source:'interpolated'};const xml=exportResolume(p);assert.equal((xml.match(/<DmxSlice /g)||[]).length,3);assert.equal((xml.match(/<DmxScreen /g)||[]).length,2);assert.match(xml,/A &amp; B &lt;test&gt;/);assert.match(xml,/name="Start Channel" T="DOUBLE" default="7" value="7"/);assert.match(xml,/name="Subnet" T="DOUBLE" default="1" value="1"/);assert.equal((xml.match(/value="TT_DISABLED"/g)||[]).length,2);const ids=[...xml.matchAll(/uniqueId="(\d+)"/g)].map(m=>m[1]);assert.equal(new Set(ids).size,ids.length);assert.match(xml,/<FixtureInstance/);assert.throws(()=>exportResolume(newProject()),/Map at least/);});
test('Resolume emits RGBA fixtures and rejects a mapped split LED',()=>{const p=newProject(),s=p.strips[0];s.type='rgba';s.points[0]={x:.5,y:.5,confidence:1,source:'manual'};assert.match(exportResolume(p),/Color Format[^>]+default="rgba"/);s.channel=511;s.universePolicy='channel';assert.throws(()=>exportResolume(p),/cannot split one LED/);});
